title: Welcome! # your name (or website title) here
logo: "/images/pic.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi, I am Adeshina Ogunmodede but most people call me "Ade" for short. I am a software developer currently
  based in Abuja, Nigeria. I began teaching myself how to code in January 2016 and I have worked professionally
  since October 2017. My experience is mostly with Java backend technologies.
  <br><br>
  I am a big fan of Rust, a language I am currently learning. I hope to work with Rust professionally some day. 
  On this site I showcase some of the small web-based projects I work on in my free time.
  <br><br>
  <a href="https://www.linkedin.com/in/adeshina-ogunmodede-195364192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 - your Google Analytics tracking ID here
