title: Welcome! # your name (or website title) here
logo: "/images/pic.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi, I am Adeshina Ogunmodede but most people call me "Ade" for short. I am a software developer with 
  years of professional experience in Java backend development. I am also an aspiring data engineer and
   a big fan of Rust. On this site I showcase some of the small projects I work on in my free time. 
  <br><br>
  <a href="https://www.linkedin.com/in/adeshina-ogunmodede-195364192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 - your Google Analytics tracking ID here
